version: 1.8.11.{build}
configuration: Release
init:
- cmd: ''
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: |
    # Install .NET 6.0 SDK
    choco install dotnet-6.0-sdk
- cmd: dotnet restore
build_script:
- cmd: dotnet build Ketarin.csproj --configuration Release --verbosity minimal
after_build:
- cmd: >-
    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.dll

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\x86\SQLite.Interop.dll

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.exe

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*.config

    7z a Ketarin.zip %APPVEYOR_BUILD_FOLDER%\Assemblies\DiffieHellman.dll
artifacts:
- path: bin\Release\Ketarin.exe
- path: bin\Release\Ketarin.exe.config
- path: bin\Release\Microsoft.Management.Infrastructure.dll
- path: bin\Release\ScintillaNET.dll
- path: bin\Release\System.Data.SQLite.DLL
- path: bin\Release\System.Management.Automation.DLL
- path: bin\Release\Tamir.SharpSSH.dll
- path: Ketarin.zip
deploy:
- provider: Environment
  name: Prerelease